### ISSUE TITLE
"Quick Start" issue

### ISSUE THREAD

**Issue by 792370706** [ivy-dl/ivy#3]
Avoid other changes when changing frameworks except ivy.set_framework(). In the example, Quick Start, if I want to run it in tensorflow, except changing 'torch' to 'tensorflow' for ivy.set_framework(), I have to change the shape of x_in from [3] to [1, 3].

By the way, if there are some updates on my application for research engineer role, please email me!

**Comment by djl11** [comment]
Hi @792370706, thanks a lot for raising this issue! A [unit test](https://github.com/ivy-dl/ivy/blob/master/ivy_tests/test_core/test_demos.py#L18) has been added to check this demo runs without error. It seems to work fine on master branch. Perhaps the error is with the latest PyPI release? Alternatively, perhaps you're using an old version of tensorflow? Maybe try upgrading tensorflow. Otherwise if it's a problem with Ivy, then the latest PyPI release will be out soon. Please raise another issue if you continue to have problems.
