### ISSUE TITLE
ivy.torch.use not exist

### ISSUE THREAD

**Issue by Leonard907** [ivy-dl/ivy#4]
I have applied to the Ivy research engineer internship and my email is s1970716@ed.ac.uk. I have worked around ivy for some time and found the idea of integrating multiple frameworks very intersting and useful. I have noticed the following error on my machine. The following code does not work properly:
```
import ivy
import torch
import numpy as np

with ivy.numpy.use:
    x = np.array([0.])
    y = ivy.cos(x) 

with ivy.torch.use:
    x = torch.tensor([0.])
    y = ivy.cos(x) 
```
The above code emits the error: `module 'ivy' has no attribute 'numpy'`. This error is only resolved when I set the framework to `numpy`. Moreover, it seems that if I set the framework to `torch`, there is still no variable named `use` in `ivy.torch`. I have looked at the implementation and found this problem a bit weird, since the `use` variable seems to be declared in each module.  

Thank you for viewing this request, if there is any update on my application, please email me, thanks.

**Comment by djl11** [comment]
Hi @Leonard907, thank you very much for helpfully raising this issue. In order to use the `use` method, it's actually necessary to first import the specific ivy backend like so: `import ivy.backend`.

Updating your example, the following code runs without error:

```
import torch
import numpy as np
import ivy.numpy
import ivy.torch

with ivy.numpy.use:
    x = np.array([0.])
    y = ivy.cos(x) 

with ivy.torch.use:
    x = torch.tensor([0.])
    y = ivy.cos(x)
```

In general, the simplest option is to use `ivy.set_framework('torch')` and `ivy.unset_framework()` before and after blocks. This removes the need to import the specific ivy backend.

However, you did helpfully raise an issue with nested calls to `use`, which has been fixed and a [unit test](https://github.com/ivy-dl/ivy/blob/master/ivy_tests/test_core/test_general.py#L53) has been added for this, so thanks for this!

**Comment by Leonard907** [comment]
Thanks. Is there any update on my application?
